CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT pk_item
            PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR,
    available   BOOLEAN,
    owner_id    BIGINT                                  NOT NULL
        CONSTRAINT users_id_fkey_items
            REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT pk_booking
            PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    BIGINT                                  NOT NULL
        CONSTRAINT items_id_fkey_bookings
            REFERENCES items (id),
    user_id    BIGINT                                  NOT NULL
        CONSTRAINT users_id_fkey_bookings
            REFERENCES users (id),
    status     varchar
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT pk_request
            PRIMARY KEY,
    description  varchar,
    requestor_id BIGINT                                  NOT NULL
        CONSTRAINT users_id_fkey_requests
            REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT pk_comments
            PRIMARY KEY,
    text      varchar,
    item_id   BIGINT                                  NOT NULL
        CONSTRAINT items_id_fkey_comments
            REFERENCES items (id),
    author_id BIGINT                                  NOT NULL
        CONSTRAINT users_id_fkey_comments
            REFERENCES users (id)
);